spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/users
    username: webstore
    password: webstore

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8010

jwt:
  privateKey: "-----BEGIN RSA PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDGrna7Ee4X0mgwTP788iLC5SgnAPfDyTvpWcGKBGvprPTV1TSShp5gNEkuM/A8JdARyA7S9GrHlrhpySQCAduxMbdoZh++NITYxZtq43wWRrmO7fBtafTrXJztVr+dSkN0bu7yiX0BxwmMPqo7Ryr9Y4CiivugvyXobu7I2CHZ2W8b3kwtKxku3VBaw3LvleP2MB6j+g4tp9SwbGMl+cFUTLAhenluG4ik0hPOdJAPToQMUOCIhCekXg1Z3wQlqjFWC0oX+RG6GRcLDHQz0lQ4I6ebzJSD7L+v8+DbBSOhSBLGeXp84ri0bdESfH1nVVTP+KdOSLhgdDgTYsl3S6LJAgMBAAECggEABPKTQlVP+Ifk0E8ainH9K51JQq9jfBymwUja6PTzOv5zml+Uz5FKoFqs99mTQewvIkI5HEe54P5/2SKJIwOo1ODIEHF6mOH17O/+zsqbbHKWbFjAg/j/gFzuC3r9io0u4NdiW+fQlRq/wh5NXuyGxYiUy3dqjLY123Pnvlijfyk/vqffFtSM6mICXAYhwP27G9MzHVOFWEs6DhWOawVziS5BDPCVWlG3VzFtPsDtELX1mo2u1YIz21GL5pfdi06df+vPDUuJBVq8yJK7BJaI8AULC039zZEdN0J94sRE2v+vROVkU90djd5QeoNQLSd3hW8Gb3xtvU0BPFJZ27+gAQKBgQDb0mQ+8mcG2lBHxa80gf16CncXAhhDvamu21r7S6uJUWZhDV0JSgR6b+/SRifCygAZ09Oouq1JQaYpTnQOzHW7CURCVJWFm+rLI0U/ZgK1aV4Cn3ryjFp3YTSTsUjKvUWIqpUwxus5oZ1l3F7Wopr7dw7TnuNHQ0XFHRRTptLnaQKBgQDnYWFOsCfgTTCuibU4Son3ewwFCkC+i4LMh1M1kOoNjyr6f8e+vpbLjdyKSdd/NcXlHuAjOZkqEY6Z+8SpjoNk9fvltS3ZyEIKIZRyZqpchk3yvCgME1lgF5PT3hqGLpeEXuzhW2MyDnFOOAflcLSYlB8uRYkDqo4NG2QUOufUYQKBgQDaWyeRD6EfwYS1hrz/X5C2xeZ+SGpp/+Cp/ONndEc05FLaXTfpnkjMhpynN2EPsTBgd3ZsyOKRPlEb/v5yJM9dt1rCuNq+GZ8loieLTn2qTrw/xsOOY7UJmNltTFGOcmy70RbZmP7YBJ4hLMJYWrWwzRdBRzdk9oI7xyMF5VTi4QKBgQCJrTQNclwH52ZUNLSULiYyEBFy3krwFmtZ8Bve/7+FGe9k5qugIB/yNxNHZfDITOLYFqsfyqIMmi3UCi9XBOnCJWwhntENiU9iX+DIwbYVIAU5riPWK50+xEi+BKabuRWHOkSRQ6OeoWFiPYzVRV7wexKiodWJTO8BdY7zSqmvgQKBgHRsGK88Jk3czXT1ZUhC/mPw5KYvKQwZI9jz0/YtxkxfzVBy8i3zuVfLRWyW62kc4Rn3lF+EaXACUPaQMsKVbnDXDlNR1fgbDOkl61wvc9yCHtXNJIU/1uHP8gt3vqc3ty9ZP6kkDqBTlgvmfmdyCROfwdvwMktRQ7n1xoayjKDe
-----END RSA PRIVATE KEY-----"
  publicKey: "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxq52uxHuF9JoMEz+/PIiwuUoJwD3w8k76VnBigRr6az01dU0koaeYDRJLjPwPCXQEcgO0vRqx5a4ackkAgHbsTG3aGYfvjSE2MWbauN8Fka5ju3wbWn061yc7Va/nUpDdG7u8ol9AccJjD6qO0cq/WOAoor7oL8l6G7uyNgh2dlvG95MLSsZLt1QWsNy75Xj9jAeo/oOLafUsGxjJfnBVEywIXp5bhuIpNITznSQD06EDFDgiIQnpF4NWd8EJaoxVgtKF/kRuhkXCwx0M9JUOCOnm8yUg+y/r/Pg2wUjoUgSxnl6fOK4tG3REnx9Z1VUz/inTki4YHQ4E2LJd0uiyQIDAQAB
-----END PUBLIC KEY-----"
  accessExpiration: 300 # 5 minutes
  refreshExpiration: 604800 # 7 days
