server:
  port: 8222


application:
  config:
    auth-url: http://localhost:8222/api/v1/auth

spring:

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/users/**
#
        - id: cart-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/carts/**
          filters:
            - JwtAuthFilter

        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
            - Method=GET
          filters:
            - JwtAuthFilter

        - id: order-lines-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**
            - Method=GET
          filters:
            - JwtAuthFilter

        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - JwtAuthFilter

        - id: product-service-category
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - JwtAuthFilter

        - id: product-service-catalog
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/catalog/**

        - id: media-service
          uri: lb:http://MEDIA-SERVICE
          predicates:
            - Path=/api/v1/media/**


#        - id: payment-service
#          uri: lb:http://PAYMENT-SERVICE
#          predicates:
#            - Path=/api/v1/payments/**