spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/media
    username: webstore
    password: webstore

    jpa:
      hibernate:
        ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8040

jwt:
  publicKey: "-----BEGIN PUBLIC KEY-----
  MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCURx9qlEbwA1WCkqGLBb3XsPLG59XKed0FzUSVhWA5BTyoepbJDPl95gnrElnPqKB0QeCDSQPm1k6zeOUdC6qmZ+dywIJ50jM1Mc0r19VlCPnXsL6q9dpo/dzYMfaZicckpWJrZP9VWUfOu0BGwWYjayhuiKwrl7ZHF/J48did1wIDAQAB
  -----END PUBLIC KEY-----"

media:
  image:
    storage-path: "C:/dev/pet_projects/webstore/services/media-service/src/main/resources/static/storage/"