spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/products
    username: webstore
    password: webstore

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: 'init'
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8020

jwt:
  publicKey: "-----BEGIN PUBLIC KEY-----
  MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCURx9qlEbwA1WCkqGLBb3XsPLG59XKed0FzUSVhWA5BTyoepbJDPl95gnrElnPqKB0QeCDSQPm1k6zeOUdC6qmZ+dywIJ50jM1Mc0r19VlCPnXsL6q9dpo/dzYMfaZicckpWJrZP9VWUfOu0BGwWYjayhuiKwrl7ZHF/J48did1wIDAQAB
  -----END PUBLIC KEY-----"

application:
  config:
    media-url: http://localhost:8040/api/v1/media