services:

  postgresql:
    container_name: ws_postgres
    image: postgres
    environment:
      POSTGRES_USER: webstore
      POSTGRES_PASSWORD: webstore
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"  # host \ container
    networks:
        - ms-webstore

  pgadmin:
    container_name: ws_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - ms-webstore

  mongodb:
    image: mongo
    container_name: ws_mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=webstore
      - MONGO_INITDB_ROOT_PASSWORD=webstore
    networks:
      - ms-webstore

  mongo-express:
    image: mongo-express
    container_name: ws_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=webstore
      - ME_CONFIG_MONGODB_ADMINPASSWORD=webstore
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - ms-webstore

  mail-dev:
    container_name: ws_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - ms-webstore

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: ws_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,INTERNAL://:9093,CONTROLLER://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:9093
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9094
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=xw7rRcehRpKQdY1NGsLIkw
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - ms-webstore

  kafka_ui:
    container_name: ws_kafka_ui
    image: provectuslabs/kafka-ui:v0.7.1
    ports:
      - "9080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9093
      - KAFKA_CLUSTERS_0_NAME=kraft
    networks:
      - ms-webstore

  keycloak:
    container_name: ws_keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9098:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - ms-webstore
    command:
      - "start-dev"

networks:
  ms-webstore:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
  kafka_data:
