spring:

  application:
    name: review-service

  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8050

application:
  config:
    product-url: http://localhost:8020/api/v1/products
    user-url: http://localhost:8010/api/v1/users